"""Create poopables table

Revision ID: 089557452cd9
Revises: 
Create Date: 2020-02-21 18:56:16.297024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '089557452cd9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poopable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poopable')
    # ### end Alembic commands ###
