"""Init

Revision ID: 1c3be18d2bd3
Revises: 
Create Date: 2020-03-05 12:44:30.935355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c3be18d2bd3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poopable',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=128), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user',
                    sa.Column('slack_user_id', sa.String(
                        length=9), nullable=False),
                    sa.PrimaryKeyConstraint('slack_user_id')
                    )
    op.create_table('log',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('last_update', sa.String(
                        length=10), nullable=False),
                    sa.Column('opened', sa.Boolean(), nullable=False),
                    sa.Column('poopable_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['poopable_id'], ['poopable.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('users_prefered_poopables',
                    sa.Column('slack_user_id', sa.String(
                        length=9), nullable=False),
                    sa.Column('poopable_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['poopable_id'], ['poopable.id'], ),
                    sa.ForeignKeyConstraint(
                        ['slack_user_id'], ['user.slack_user_id'], ),
                    sa.PrimaryKeyConstraint('slack_user_id', 'poopable_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_prefered_poopables')
    op.drop_table('log')
    op.drop_table('user')
    op.drop_table('poopable')
    # ### end Alembic commands ###
