"""add open to poopable

Revision ID: b50a36a67bf9
Revises: 06a9c825828a
Create Date: 2020-02-21 19:58:57.342160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b50a36a67bf9'
down_revision = '06a9c825828a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poopable', sa.Column('opened', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('poopable', 'opened')
    # ### end Alembic commands ###
